### ISSUE TITLE
🔀 Aceptar cambios de un _pull request_

### ISSUE THREAD

**Issue by mvillasante** [CarlosTMX/cetys_cat_recognition#3]
Buen día @CarlosTMX. 

Somos Memo (@MemoOlv) y Mario, formamos parte del equipo de Ciencia de Datos de GECI.
En conjunto con @nepito estamos dando seguimiento a tus dudas.

Este _issue_ lo creamos para ayudarte a hacer _merge_ (fusionar) un _pull request_  a tu código; así puedes aceptar los cambios que proponemos en tu repositorio.

A continuación describimos los pasos necesarios para aceptar los cambios. 

---

### 1. 🤺 Ingresa a la pestaña _Pull requests_.
![image (1)](https://github.com/CarlosTMX/cetys_cat_recognition/assets/42744723/03ee669b-681f-44ee-a977-014695956280)

### 2. 👆🏼Selecciona un _pull request_ en específico.
![image (2)](https://github.com/CarlosTMX/cetys_cat_recognition/assets/42744723/6e73711a-d5cb-4986-bfda-bec876118f8d)

### 3. 💬 Sección de "Conversación" 
![image (3)](https://github.com/CarlosTMX/cetys_cat_recognition/assets/42744723/c18fd6ce-b98a-441a-ba3f-dd6235dffe00)
Aquí podrás encontrar una descripción de los cambios que incorporarías a tu repositorio si aceptas el _pull request_.
Esta pestaña es similar a los _issues_, aquí podremos discutir sobre los cambios propuestos.

### 4. 💱En la sección _Files changed_ podrás ver las líneas que se pretenden modificar.
![image (4)](https://github.com/CarlosTMX/cetys_cat_recognition/assets/42744723/3dc50444-2342-4b4b-957f-1a13a5a59286)
Las líneas con un signo **"-"** fueron eliminadas y el signo **"+"** indica que agregamos la línea o hicimos alguna modificación. 
En la captura de pantalla anterior podemos ver que cambiamos la imagen de python 3 por la imagen oficial de ultralytics.

### 5. 🔀Aceptando los cambios
![image (6)](https://github.com/CarlosTMX/cetys_cat_recognition/assets/42744723/9d324ac4-ab19-488e-bc50-a95a5b9a8b6e)
_*Esta captura solamente es ilustrativa, no corresponde exactamente a lo que verás en tu repositorio._

Al hacer clic en el botón de arriba tendrás tres opciones para hacer la fusión 🐉 (_merge_). Deberás seleccionar la opción **Combinar solicitud de incorporación de cambios** (_Create a merge commit_). Esto incorporará los cambios a la rama base de tu repositorio. Te recomendamos agregar un comentario que describa la razón de los cambios.

Abajo encontrarás la referencia oficial de la ayuda de GitHub (🐙+🐈‍⬛) y también encontrarás el _link_ al _pull request_.
Estamos al pendiente de cualquier duda que pueda surgir. 

Saludos.

## ⏩ Referencias
- #2 
- [Mergin a pull request](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request?tool=webui)

**Comment by CarlosTMX** [comment]
Hola Memo y Mario @mvillasante,

¡Mucho gusto! Gracias por la información, si estaba al tanto de como hacer un merge, lo había investigado previamente. Nunca había trabajado directo con github, solamente con Git y SourceTree hace ya algunos años, por lo mismo estoy aprovechando para actualizarme en el tema. 

Reitero, muchas gracias por el apoyo.

**Comment by nepito** [comment]
Muchas gracias @CarlosTMX por tu respuesta. Como este tema ya está resuelto, voy a cerrar este _issue_. Podemos seguir la plática en el _pr_:
- #4
