### ISSUE TITLE
Asegurar que evaluamos las fotos correctas

### ISSUE THREAD

**Issue by MemoOlv** [CarlosTMX/cetys_cat_recognition#5]
👋🏿 Hola @CarlosTMX 

🎉🎉🎉 Felicidades 🎉🎉🎉

Ya pudimos echar a andar el [clasificador](https://github.com/IslasGECI/ctf_cat_recognition/actions/runs/9087936726/job/24976616653#step:11:66). Ésta era la parte más difícil. 

![cetys_resultados](https://github.com/CarlosTMX/cetys_cat_recognition/assets/53709062/80477d84-78ea-48a0-8eb5-55dff57d02ca)

### 📋 Pendientes

- [ ] Copiar las fotos con gatos a la carpeta `cat_detected`

### 🚚 Copiar las fotos con gatos a la carpeta `cat_detected`

Creemos que los cálculos de la evaluación son incorrectos. Para que el clasificador evalúe correctamente tu modelo, por favor asegúrate que solamente estén las fotos **con gatos** en la carpeta `cat_detected`.

**Comment by CarlosTMX** [comment]
Hola @MemoOlv, @nepito, @mvillasante 

Es un alivio ver que ya está medianamente funcionando, pero como dices todavía hay cosas pendientes. Desde ayer estuve haciendo pruebas e investigando sobre algunos errores que están sucediendo a la hora de la clasificación, los cuales aquí enlisto:

- Ciertamente todavía no estoy almacenando las fotos exclusivas de gato, eso es un cambio relativamente sencillo, pero de momento no me quería enfocar en ello porque simplemente quería reproducir un escenario de funcionamiento típico. Próximamente haré ese cambio para volver a generar los cálculos.

- En la etapa de Classify photos hay un warning que puede ser significativo, el cual se muestra en la imagen de abajo:
![image](https://github.com/CarlosTMX/cetys_cat_recognition/assets/156007230/66591a70-a676-43d7-993b-a4b711782bd2)
Encontré dos casos similares [https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/157](url) y [https://github.com/ultralytics/ultralytics/issues/2571](url), aunque ninguno con una resolución definitiva, más allá de actualizar ultralytics. ¿Qué versión se está utilizando actualmente? Quizá la imagen de ultralytics que se instala, al ser más ligera, no está del todo actualizada y no cuenta con las últimas dependencias.  De ser posible, es algo que me gustaría verificar y corregir, ya que me da a entender que el modelo pre-entrenado no está funcionando debidamente, aunque hasta ahora no he podido encontrar que tan importante pueda ser este detalle.

- El otro detalle es que están apareciendo archivos con corrupción de datos que no pueden ser procesados debidamente. Esto es lo que habíamos platicando anteriormente @nepito, lo cual pude corregir después de editar las fotografías para el entrenamiento. Aunque no fueron muchos los casos (5 fotografías), parece ser algo recurrente y valdría la pena encontrar la raíz del problema para futuras análisis. 
![image](https://github.com/CarlosTMX/cetys_cat_recognition/assets/156007230/b79d5e3b-aae5-4876-9e50-84a5b7c4c257)

Por último, tengo una duda con respecto a las las instrucciones de cp -r en el Makefile. Entiendo que eso hace una copia de los archivos en su directorio (de lo contrario no haría ningún cálculo) y debería hacer lo mismo para la carpeta Backup_prediction/, sin embargo no veo esos resultados en la carpeta del repositorio. Supuse que era un tema de sincronización, que me haría falta hacer un pull, pero no parece ser el caso. Es probable que esto sea algo muy simple, pero ante el desconocimiento prefiero preguntar.

**Comment by nepito** [comment]
Hola @CarlosTMX, esto pinta cada vez mejor 😎.

Antes que nada, déjame agradecerte tu respuesta tan detallada. Nos facilitas mucho poderte ayudar.

---

Ahora, dando respuesta a tus inquietudes:

 1. > Ciertamente todavía no estoy almacenando las fotos exclusivas de gato, eso es un cambio relativamente sencillo

Nosotros te sugerimos que corregir lo de las carpetas sea el siguiente cambio. Así ya tendremos los resultados buenos de la evaluación del clasificador. También podremos ver el efecto de los siguientes cambios en esa evaluación.

Tendremos la evaluación base cuando solo las fotos con gatos detectados estén en la carpeta `cat_detected`. Así podremos ver qué efecto tienen en la evaluación las siguientes modificaciones que hagamos. Así compararemos las siguientes evaluaciones contra la evaluación base. 

Así podremos utilizar la evaluación base para no ir dando bastonazos de ciego.  



2. > En la etapa de Classify photos hay un warning que puede ser significativo

Los warning los podemos resolver desde el **Dockerfile**. Para saber si es o no significativo, necesitamos que solo las fotos con gatos detectados estén en la carpeta `cat_detected`. Con eso aseguramos que la evaluación es la correcta.



3. > El otro detalle es que están apareciendo archivos con corrupción de datos

Tienes razón, son solo 2.6% de las fotos y parece que eso será un comportamiento recurrente. Para saber que tanto impacto tiene contar (o no) las fotos corruptas, lo primero es tener evaluación base del desempeño del clasificador.

Aun estamos en la espera de la nueva colección de fotos que nos sugeriste. La colección que está bien equilibrada: fotos con gatos, sin gatos, de día y de noche. Pero una vez que esté todo en su lugar (las fotos con gatos en la carpeta `cat_detected`), no tendrás que preocuparte de este cambio. 


4.  >  tengo una duda con respecto a las las instrucciones de cp -r en el Makefile

Las fotos no se consignan en el repositorio. El _GitHub Actions_ borra todo de sus servidores. Entonces, no hay ningún registro de las fotos por ningún lado (_behind the wall_). Al final,  `paco_el_chato` espera que las fotos con gatos detectados estén en la carpeta `cat_detected`. Es por eso que el siguiente cambio tiene que ser mover las fotos con gatos detectados para que las pueadan ver nuestros compañeros en campo.

Abajo te dejamos la referencia a la que nosotros siempre recurrimos para refrescar los comados `mv` y `cp` en Linux.

Seguiremos al pendiente.

## Referencias
[Linux fundamentals: How to copy, move, and rename files and directories](https://www.redhat.com/sysadmin/move-copy-files-linux)

**Comment by CarlosTMX** [comment]
Hola @nepito @MemoOlv @mvillasante,

Listo, ya hice la modificación y los resultados fueron buenos. 
![image](https://github.com/CarlosTMX/cetys_cat_recognition/assets/156007230/19ce5ee1-4968-48ba-9acd-f4c235c1b316)

Creo que es posible mejorar todavía más los resultados, aunque para eso necesitaría poder ver las fotos que está procesando, así como sus resultados, para poder hacer un análisis e interpretación. 

¿Cuál sería el siguiente paso? o ¿qué otra prueba les gustaría realizar?

**Comment by MemoOlv** [comment]
Hola @CarlosTMX 👋🏾

Les resultados se ven muy bien. 😍😍

Vemos que:
-  _Sensitivity_ pasó de 39% a 80%
- _Balanced accuracy_ pasó de 70% a 88%

Estos resultados ayudarán mucho a nuestros compañeros en campo. Esta es una pieza importante en el proyecto de restauración en Isla Guadalupe. 

Vamos a cerrar este _issue_ porque ya atendiste el asunto. 🦾🙌🏼

En el estado actual ya cumple con la interfaz que `paco_el_chato` espera y ya tenemos una evaluación base. Cualquier otra mejora que quieras hacer podremos ver su impacto comparándola con el estado actual. 

Muchas felicidades y gracias por considerar nuestras sugerencias. 🎉🎉

**Comment by CarlosTMX** [comment]
Hola @MemoOlv,

Gracias a ustedes por el apoyo, me da gusto que se hayan logrado las expectativas!

Ya acepte el PR que me mandaste y efectivamente ya no tenemos el Warning, lo cual seguramente es positivo, aunque de momento no se ve reflejado en los porcentajes de evaluación. Sin embargo, estoy seguro que esto no puede ser más que benéfico a la larga. 

Ya solo queda pendiente el tema de las imágenes corruptas. Dado que ustedes saben si dichas imágenes contienen gato o no, de momento se podría hacer una estimación del impacto en los porcentajes que se están mostrando y así valorar si quisieran hacer alguna modificación. Es posible que se corrija el problema con esas fotografías si las abren con un editor (Adobe Illustrator/Photshop, Inkscape, etc.) y las guardan otra vez como .jpg, ya que en ocasiones estos editores automáticamente corrigen errores de corrupción en el formato de compresión. 

Sigo al pendiente por si todavía podemos mejorar estos porcentajes, lo cual creo que podría ser viable dados los resultados que yo obtuve en mis pruebas internas.
![image](https://github.com/CarlosTMX/cetys_cat_recognition/assets/156007230/630ff263-b680-412d-b2b3-02b711043b03)
